### PR TITLE
add module preloading

### PR DESCRIPTION
**Pull request by qdouble**

### CODE REVIEW

**Comment by DzmitryShylovich** [comment]
Does it work in aot?

**Comment by qdouble** [comment]
yeah, it seems they fixed the issue that was in rc

**Comment by DzmitryShylovich** [comment]
so https://github.com/angular/angular/issues/12141 can be closed

**Comment by qdouble** [comment]
@DzmitryShylovich can you double check that it works for you before I close?

**Comment by DzmitryShylovich** [comment]
sure

**Pull request merged**
